### ISSUE TITLE
Crashed at startup

### ISSUE THREAD

**Issue by zhenyatk** [jehy/hass-addons#1]
Crashed at startup
Log has a clear text secrets data and reason:
position: 1448,
    line: 58,
    column: 41,
    snippet: ' 56 |  ... \n' +
      ' 57 |  ... eg\n' +
      ' 58 |  ... m: telegram\n' +
      ' 59 |  ... : !secret telegram_chat_id_teg\n' +
      '-----------------------------------------^\n' +
      ' 60 |  ... \n' +
      ' 61 |  ... a_notify'
  }
}

Node.js v18.19.0
[15:07:20] WARNING: dbstats crashed, halting add-on

**Comment by jehy** [comment]
Hi! Please check current version, I rewrote config preprocessing from scratch.

**Comment by zhenyatk** [comment]
buffer: 'default_config:\n' +
      'tts:\n' +
      '  - platform: google_translate\n' +
      '  - platform: reversotts\n' +
      "    language: 'Alyona-Russian'\n" +
      '    pitch: "100"\n' +
      '    bitrate: "128k"\n' +
      'frontend:\n' +
      '  extra_module_url:\n' +
      '    - /local/card-mod.js\n' +
      'homeassistant:\n' +
      '  customize:\n' +
      '    valve.hot_water:\n' +
      '      device_class: water\n' +
      '    valve.cold_water:\n' +
      '      device_class: water\n' +
      'telegram_bot:\n' +
      '  - platform: polling\n' +
      '    parse_mode: html\n' +
      '    api_key: XXXXXX\n' +
      '    allowed_chat_ids:\n' +
      '      - XXXXXX\n' +
      '      - -XXXXXXX\n' +
      'notify:\n' +
      '  - name: Home Assistant\n' +
      '    platform: html5\n' +
      '    vapid_pub_key: XXXXXX\n' +
      '    vapid_prv_key: XXXXXX\n' +
      '    vapid_email: zhenya.tkachenko@gmail.com\n' +
      '  - name: teg\n' +
      '    platform: telegram\n' +
      '    chat_id: !secret telegram_chat_id_teg\n' +
      '  - name: ha_notify\n' +
      '    platform: telegram\n' +
      '    chat_id: -XXXXXX\n' +
      'http:\n' +
      '  use_x_forwarded_for: true\n' +
      '  trusted_proxies:\n' +
      '    - 172.30.33.0/24\n' +
      'yandex_smart_home:\n' +
      '  notifier:\n' +
      '    - oauth_token: XXXXXXX\n' +
      '      skill_id: XXXXXX\n' +
      '      user_id: XXXXXX\n' +
      'yandex_station:\n' +
      '  include:\n' +
      '    - Вентилятор\n' +
      '  media_source:\n' +
      '    - title: Произнеси текст  # обязательное поле\n' +
      '      media_content_type: text  # обязательное поле\n' +
      '      thumbnail: https://brands.home-assistant.io/_/tts/icon.png\n' +
      '    - title: Выполни команду\n' +
      '      media_content_type: command\n' +
      '      thumbnail: https://brands.home-assistant.io/_/automation/icon.png\n' +
      'command_line:\n' +
      '  - sensor:\n' +
      '      name: Server Temperature (x86_pkg_temp)\n' +
      '      command: "cat /sys/class/thermal/thermal_zone1/temp"\n' +
      '      unit_of_measurement: "°C"\n' +
      '      value_template: "{{ value | multiply(0.001) | round(2, default=0) }}"\n' +
      '  - sensor:\n' +
      '      name: Server Temperature (acpitz)\n' +
      '      command: "cat /sys/class/thermal/thermal_zone0/temp"\n' +
      '      unit_of_measurement: "°C"\n' +
      '      value_template: "{{ value | multiply(0.001) | round(2, default=0) }}"\n',
    position: 848,
    line: 31,
    column: 41,
    snippet: ' 29 |  ... mail: zhenya.tkachenko@gmail.com\n' +
      ' 30 |  ... eg\n' +
      ' 31 |  ... m: telegram\n' +
      ' 32 |  ... : !secret telegram_chat_id_teg\n' +
      '-----------------------------------------^\n' +
      ' 33 |  ... a_notify\n' +
      ' 34 |  ... m: telegram'
  }
}

Node.js v18.19.0
[22:35:57] WARNING: dbstats crashed, halting add-on
[22:35:57] INFO: dbstats stopped, restarting...
s6-rc: info: service legacy-services: stopping
2024/02/05 22:35:57 [notice] 176#176: signal 15 (SIGTERM) received from 174, exiting
2024/02/05 22:35:57 [notice] 194#194: exiting
2024/02/05 22:35:57 [notice] 194#194: exit
2024/02/05 22:35:57 [notice] 176#176: signal 17 (SIGCHLD) received from 194
2024/02/05 22:35:57 [notice] 176#176: worker process 194 exited with code 0
2024/02/05 22:35:57 [notice] 176#176: exit
if: fatal: unable to spawn s6-test: No such file or directory
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by jehy** [comment]
It was an issue with multiple usage of the same secret. My bad, I didn't expect it. Fixed now :)
