### ISSUE TITLE
Addon crashed with recorder configured with !include tag

### ISSUE THREAD

**Issue by to4ko** [jehy/hass-addons#2]
Addon crashed in case if:
1. home_assistant.db exist but empty
2. recorder configured via !include tag https://github.com/to4ko/myconfig/blob/master/configuration.yaml#L68
![image](https://github.com/jehy/hass-addons/assets/45161980/89bcffcf-6b1d-4e66-a718-d70b342cc9b6)

Might be easier to have addon configuration available via gui.

**Comment by jehy** [comment]
Thanks for the details! Should be fine in new version, please check it.

**Comment by to4ko** [comment]
updated to latest version - 

![image](https://github.com/jehy/hass-addons/assets/45161980/00ac4617-ae27-4f59-aff4-f22d27e9f735)

**Comment by to4ko** [comment]
some additional logs from portainer

s6-rc: info: service legacy-services successfully started
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] database options from env not found, checking config
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] config file found, parsing
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] Input: abspath /homeassistant/configuration.yaml homeDir /homeassistant
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] found and parsed secrets file
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] 225 secrets found for file /homeassistant/configuration.yaml
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] Input: abspath /homeassistant/my_config/customize.yaml homeDir /homeassistant
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] going up to /homeassistant/
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] found and parsed secrets file
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] 225 secrets found for file /homeassistant/my_config/customize.yaml
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] Input: abspath /homeassistant/my_config/customize_glob.yaml homeDir /homeassistant
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] 225 secrets found for file /homeassistant/my_config/customize_glob.yaml
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] Input: abspath /homeassistant/my_config/http.yaml homeDir /homeassistant
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] 225 secrets found for file /homeassistant/my_config/http.yaml
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] Input: abspath /homeassistant/my_config/automation homeDir /homeassistant
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] Input: abspath /homeassistant/my_config/automation/emergency_main.yaml homeDir /homeassistant
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] going up to /homeassistant/my_config/
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] going up to /homeassistant/
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] found and parsed secrets file
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] 225 secrets found for file /homeassistant/my_config/automation/emergency_main.yaml
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] Input: abspath /homeassistant/my_config/automation/bathroom/fan.yaml homeDir /homeassistant
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] going up to /homeassistant/my_config/automation/
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] going up to /homeassistant/my_config/
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] 225 secrets found for file /homeassistant/my_config/automation/bathroom/fan.yaml
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] Input: abspath /homeassistant/my_config/automation/bathroom/light.yaml homeDir /homeassistant
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] 225 secrets found for file /homeassistant/my_config/automation/bathroom/light.yaml
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] Input: abspath /homeassistant/my_config/automation/bathroom/scale.yaml homeDir /homeassistant
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] 225 secrets found for file /homeassistant/my_config/automation/bathroom/scale.yaml
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] Input: abspath /homeassistant/my_config/automation/bathroom/valve_test.yaml homeDir /homeassistant
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] 225 secrets found for file /homeassistant/my_config/automation/bathroom/valve_test.yaml
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] Input: abspath /homeassistant/my_config/automation/bathroom/washing_machine.yaml homeDir /homeassistant
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] 225 secrets found for file /homeassistant/my_config/automation/bathroom/washing_machine.yaml
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] Input: abspath /homeassistant/my_config/automation/hall_big/domofon.yaml homeDir /homeassistant
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] going up to /homeassistant/my_config/automation/
[Nest] 177  - 02/05/2024, 10:23:48 PM     LOG [ConfigService] 225 secrets found for file /homeassistant/my_config/automation/hall_big/domofon.yaml
/usr/src/app/node_modules/js-yaml/lib/loader.js:187
  throw generateError(state, message);
  ^
YAMLException: unknown tag !<!secret> (33:43)
 30 |  ...         title: Open
 31 |  ...         authenticationRequired: false
 32 |  ...         activationMode: background
 33 |  ...     image: !secret window_snap  
-----------------------------------------^
 34 |  ... service: notify.telegram_cam
 35 |  ... data:
    at generateError (/usr/src/app/node_modules/js-yaml/lib/loader.js:183:10)
    at throwError (/usr/src/app/node_modules/js-yaml/lib/loader.js:187:9)
    at composeNode (/usr/src/app/node_modules/js-yaml/lib/loader.js:1521:7)
    at readBlockMapping (/usr/src/app/node_modules/js-yaml/lib/loader.js:1164:11)
    at composeNode (/usr/src/app/node_modules/js-yaml/lib/loader.js:1441:12)
    at readBlockMapping (/usr/src/app/node_modules/js-yaml/lib/loader.js:1164:11)
    at composeNode (/usr/src/app/node_modules/js-yaml/lib/loader.js:1441:12)
    at readBlockMapping (/usr/src/app/node_modules/js-yaml/lib/loader.js:1164:11)
    at composeNode (/usr/src/app/node_modules/js-yaml/lib/loader.js:1441:12)
    at readBlockSequence (/usr/src/app/node_modules/js-yaml/lib/loader.js:1008:5) {
  reason: 'unknown tag !<!secret>',

{
    name: null,
    buffer: '  - alias: hall_big_domofon_incoming_call\n' +
      '    id: hall_big_domofon_incoming_call\n' +
      '    initial_state: true\n' +
      '    mode: single\n' +
      '    max_exceeded: silent\n' +
      '    trigger:\n' +
      '      - platform: state\n' +
      '        entity_id: binary_sensor.esp32_domofon_incomingcall\n' +
      "        to: 'on'\n" +

**Comment by jehy** [comment]
Include tags are supported now. As for the troublw with yaml - I created another issue https://github.com/jehy/hass-addons/issues/3
